config/routes.rb
Rails.application.routes.draw do
  # get "home/index"
  # get "users/index"
  # get "users/show"
  # get "users/new"
  # get "users/edit"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/articles" => "articles#index"
  get "/articles/new" => "articles#new", as: 'new_article'
  post "/articles" => "articles#create", as: 'create_article'
  get "/articles/:id" => "articles#show", as: "article"
  get "/articles/:id/edit" => "articles#edit", as: "edit_article"
  patch "/articles/:id" => "articles#update"
  put "/articles/:id" => "articles#update"
  delete "/articles/:id" => "articles#delete", as: "delete_article"

  # Users routes (new routes to add)
  get "/users" => "users#index"
  get "/users/new" => "users#new", as: "new_user"
  post "/users" => "users#create", as: "create_user"
  get "/users/:id" => "users#show", as: "user"
  get "/users/:id/edit" => "users#edit", as: "edit_user"
  patch "/users/:id" => "users#update"
  put "/users/:id" => "users#update"
  delete "/users/:id" => "users#destroy", as: "delete_user"

    resources :articles do
    resources :comments, only: [:create ]
    
  end
  root "home#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :article

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :articles

  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @comments = @article.comments
        @user = @article.user
    end

    def new
        @article = Article.new
    end

    def create
         @article = Article.new(article_params)
         @article.user = User.first || User.create(username: "user-#{SecureRandom.hex(10)}")
        # @article.name = params[:name]
        # @article.body = params[:body]

        if @article.save
            puts "saved"
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    def delete
        @article = Article.find(params[:id])
        @article.destroy
            redirect_to articles_path
    end

    private 
    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    


    if @comment
      redirect_to @article
    else
      render "articles/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<style>

#storypreview {
overflow: hidden;
text-overflow: ellipsis;
max-width: 75ch;
white-space: nowrap;
}

</style>

<tr>
    <td><%= article.name %></td>
    <td id="storypreview"><%= article.body %></td>
    <td><%= link_to 'Read', article_path(article.id) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td> 
    <td><%= button_to 'Delete', delete_article_path(article.id), method: :delete %> </td>
</tr>

app/views/articles/edit.html.erb
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'shared/form', f: f  %>
  <% end %>

app/views/articles/index.html.erb
<style>

 * {
  color: #820f17
  background-color: #f5e9dc;
}

table {
  margin: 0 auto;
  border-collapse: collapse;
}

th {
  text-align: center;
}
</style>

<table>
  <thead>

    <tr>
      <th>Title</th>
      <th>Story Preview</th>
      <th><%= link_to 'Create a Story', new_article_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <%= render "article", article: article %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>
<%= render 'shared/form', f: f  %>
  <% end %>



app/views/articles/show.html.erb
<style>
* {
  text-align: center;
}

body {
  text-align: center;
}

table {
  margin: 0 auto;
  margin-left: 200px;
  margin-right: 200px;
}

form {
  display: inline-block;
  text-align: left;
  margin: 20px auto;
}
</style>


<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @article.name %> </td>
        </tr>
        <tr>
          <td>
            <p><strong>Written by:</strong> <%= @article.user.username %></p>
            <strong>Story Content</strong>
          </td>
        </tr>
        <tr>
        <td><p><%= @article.body %> </p></td>
        </tr>
      </tr>
  </tbody>
</table>

    
<h2>Comments</h2>
<% @comments.each do |comment| %>
  <div class="comment">
    <p><strong><%= comment.user&.username %></strong></p>
    <p><%= comment.body %></p>
  </div>
<% end %>


<h3>Add a comment:</h3>
 <%= form_with(model: [@article, Comment.new], local: true) do |form| %>
  <p>
     <%= form.label :user_id, "Select User:" %>
    <%= form.select :user_id, options_from_collection_for_select(User.all, :id, :username) %>
  </p>
    <%= form.text_area :body, rows: 3 %>
  </p>
  <p>
    <%= form.submit "Post Comment" %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
  <div class="comment">
    <p><%= comment.body %></p>
  </div>
<% end %>

app/views/home/index.html.erb
<style>
    *{
        text-align: center;
    }
</style>



<p>One Shot Stories</p>
<%= link_to "Read Stories", articles_path %>
<%= link_to "Users", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Article Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
        <link rel="icon" href="/icon.svg" type="image/svg+xml">
            <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, :index, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= "#{controller_name}-#{action_name}"%>">
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<style>
* {
  text-align: center;
}

</style>



<p>
  <%= f.label :name, "Title" %> <br/>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body, "Story Content" %> <br/>
  <%= f.text_field :body %>
</p>

<p>
  <%= f.submit "Publish"%>
</p>

app/views/shared/_formusers.html.erb
<style>
* {
  text-align: center;
}

</style>

<p>
  <%= f.label :username %> <br/>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :password %> <br/>
  <%= f.text_field :password %>
</p>

<p>
  <%= f.submit %>
</p>

app/views/users/_user.html.erb
<style>
* {
  text-align: center;
}

</style>

<td><%= user.username %></td>
<td><%= user.password %></td>

app/views/users/_users.html.erb
<style>
* {
  text-align: center;
}

</style>

<% @users.each do |user| %>
<tr>
<td><%= user.username %></td>
<td><%= user.password.tr('aA-zZ', '*') %></td>
<td><%= link_to 'Show', user_path(user) %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= button_to 'Delete', delete_user_path(user.id), method: :delete %> </td>
<% end %>
</tr>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/formusers', f: f  %>
  <% end %>

  

app/views/users/index.html.erb
<style>
table {
  margin: 0 auto;
  border-collapse: collapse;
}

th {
  text-align: center;
}
</style>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th><%= link_to 'Create User', new_user_path %></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <%= render "users", users: @users %>
      </tr>
  </tbody>
</table>

app/views/users/new.html.erb
<%= form_with scope: :user, url: create_user_path, local: true do |f| %>
<%= render 'shared/formusers', f: f  %>
  <% end %>

app/views/users/show.html.erb
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @user.username %> </td>
        <td><%= @user.password %> </td>
      </tr>
  </tbody>
</table>